name: Combine JSON Files

on:
  push:
    branches:
      - main  # Burada 'main' branch'ini hedefliyoruz
      
permissions:
  contents: write  # GitHub Actions botuna yazma izni verin
  
jobs:
  combine_json_files:
    runs-on: ubuntu-latest

    steps:
      # Yalnızca "kaynak" Klasörünü Çek
      - name: Set up git and sparse-checkout
        run: |
          git init
          git remote add origin https://github.com/benolanben/atesiask.git
          git config core.sparseCheckout true
          echo "kaynak" >> .git/info/sparse-checkout
          git pull origin main

      # JSON Dosyalarını Kontrol Et
      - name: Validate JSON Files
        run: |
          echo "Validating baska.json..."
          jq '.' kaynak/baska.json || { echo "Error in baska.json"; exit 1; }
          echo "Validating yunus.json..."
          jq '.' kaynak/yunus.json || { echo "Error in yunus.json"; exit 1; }

      # JSON Dosyalarını Birleştir
      - name: Combine "sesler" Arrays Sequentially
        run: |
          echo "Combining sesler from JSON files..."
          mkdir -p kaynak  # "kaynak" klasörünün varlığını garantiye al
      
          # İlk olarak baska.json dosyasını yeni.json'a yazarak başla
          jq '{sesler: .sesler}' kaynak/baska.json > kaynak/yeni.json || { echo "Failed to write baska.json"; exit 1; }
      
          # Şimdi yunus.json dosyasındaki sesleri mevcut yeni.json'a ekle
          jq '.sesler' kaynak/yunus.json | jq -s '.[0] + {sesler: .[1] + .sesler}' kaynak/yeni.json - > kaynak/yeni.json.temp || { echo "Failed to append yunus.json"; exit 1; }
          
          # Sonucu yeni.json olarak güncelle
          mv kaynak/yeni.json.temp kaynak/yeni.json
      
          echo "Successfully combined JSON files into kaynak/yeni.json."





      # Değişiklikleri Commit Et ve Pushla
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kaynak/yeni.json
          git commit -m "Combine sesler arrays into yeni.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/benolanben/atesiask.git HEAD:main

