name: Combine JSON Files

on:
  push:
    branches:
      - main  # Burada 'main' branch'ini hedefliyoruz

jobs:
  combine_json_files:
    runs-on: ubuntu-latest

    steps:
      # Yalnızca "kaynak" Klasörünü Çek
      - name: Set up git and sparse-checkout
        run: |
          git init
          git remote add origin https://github.com/benolanben/atesiask.git
          git config core.sparseCheckout true
          echo "kaynak" >> .git/info/sparse-checkout
          git pull origin main
          
      # JSON Dosyalarını Birleştir
      - name: Combine "isaretler" Arrays
        run: |
          mkdir -p output
          jq -s '{isaretler: map(.isaretler) | add}' kaynak/baska.json kaynak/saz.json > output/yeni.json
          
      # Değişiklikleri Commit Et ve Pushla
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/yeni.json
          git commit -m "Combine isaretler arrays into yeni.json"
          git push
