name: Combine JSON Files

on:
  push:
    branches:
      - main

jobs:
  combine_json_files:
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Yalnızca kaynak Klasörünü Checkout Et
      - name: Checkout "kaynak" directory only
        uses: actions/checkout@v2
        with:
          # Sadece "kaynak" klasörünü indir
          path: kaynak
          sparse-checkout: true
          fetch-depth: 1
          sparse-checkout-patterns: |
            kaynak/

      # 2. Adım: JSON Dosyalarını Birleştir
      - name: Combine "isaretler" Arrays
        run: |
          mkdir -p output
          jq -s '{isaretler: map(.isaretler) | add}' kaynak/baska.json kaynak/saz.json > output/yeni.json

      # 3. Adım: Değişiklikleri Commit Et ve Pushla
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/yeni.json
          git commit -m "Combine isaretler arrays into yeni.json"
          git push
