name: Combine JSON Files

on:
  push:
    branches:
      - main  # Burada 'main' branch'ini hedefliyoruz
    paths:
      - kaynak/**  # Sadece 'kaynak' klasörü içindeki dosyalar değiştiğinde çalışacak
      
permissions:
  contents: write  # GitHub Actions botuna yazma izni verin
  
jobs:
  combine_json_files:
    runs-on: ubuntu-latest

    steps:

      # Eğer sozler.json veya fotograflar.json dosyaları değiştiyse, iş akışını durdur
      - name: Check if sozler.json or fotograflar.json changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep -qE 'kaynak/(sozler.json|fotograflar.json)'; then
            echo "sozler.json veya fotograflar.json değişmiş. İşlem durduruluyor."
            exit 0
          fi
          
      # Yalnızca "kaynak" Klasörünü Çek
      - name: Set up git and sparse-checkout
        run: |
          git init
          git remote add origin https://github.com/benolanben/atesiask.git
          git config core.sparseCheckout true
          echo "kaynak" >> .git/info/sparse-checkout
          git pull origin main

      # JSON Dosyalarını Kontrol Et
      - name: Validate JSON Files
        run: |
          echo "Validating baska.json..."
          jq '.' kaynak/baska.json || { echo "Error in baska.json"; exit 1; }
          echo "Validating yunus.json..."
          jq '.' kaynak/yunus.json || { echo "Error in yunus.json"; exit 1; }

      # JSON Dosyalarını Birleştir
      - name: Combine "sesler" Arrays
        run: |
          echo "Combining sesler from JSON files..."
          mkdir -p kaynak  # "kaynak" klasörünün varlığını garantiye al
      
          # İlk olarak baska.json dosyasını fihimafih.json'a yaz
          jq '{sesler: .sesler}' kaynak/baska.json > kaynak/fihimafih.json || { echo "Failed to write baska.json"; exit 1; }
      
          # Diğer tüm JSON dosyalarını fihimafih.json'daki 'sesler' listesine sırayla ekle
          for file in yunus.json aheng.json cocuk.json cuma.json hakikat.json hu_diyelim.json mevlana.json \
                      muharrem.json nezih.json niyazi.json nutkuserif.json ramazan.json saz.json tsm.json fihimafih_mestmp3.json
          do
            jq '.sesler' "kaynak/$file" | jq -s '.[0] + {sesler: (.[0].sesler + .[1])}' kaynak/fihimafih.json - > temp.json \
              && mv temp.json kaynak/fihimafih.json || { echo "Failed to append $file"; exit 1; }
          done

              # Birleştirilmiş verinin uzunluğunu yazdır
          echo "The length of the 'sesler' array in fihimafih.json is:"
          jq '.sesler | length' kaynak/fihimafih.json
          
          echo "Successfully combined JSON files into kaynak/fihimafih.json."



      # Değişiklikleri Commit Et ve Pushla
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kaynak/fihimafih.json

          # Değişiklik olup olmadığını kontrol et
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Combine sesler arrays into fihimafih.json"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/benolanben/atesiask.git HEAD:main
          fi
