name: Generate Images JSON

on:
  push:
    branches:
      - main
    paths:
      - medya/atesiask/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  
jobs:
  generate_images_json:
    runs-on: ubuntu-latest

    steps:
      - name: Sparse Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /medya/atesiask/
            /medya/images.json
          sparse-checkout-cone-mode: false
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get install imagemagick jq -y

      - name: Create images.json
        run: |
          image_list=$(find medya/atesiask -type f \( -iname "*.jpg" -o -iname "*.png" \))
          echo '{ "isaretler": [' > medya/images.json
          for image in $image_list; do
            dimensions=$(identify -format '%w %h' "$image")
            filename=$(basename "$image")
            timestamp="null"
            
            if [[ "$filename" =~ -([0-9]+)\.[a-zA-Z]+$ ]]; then
              timestamp="${BASH_REMATCH[1]}"
            fi

            echo "  {\"width\": \"${dimensions% *}\", \"height\": \"${dimensions#* }\", \"path\": \"$filename\", \"timestamp\": $timestamp}," >> medya/images.json
          done
          sed -i '$ s/,$//' medya/images.json
          echo ']}' >> medya/images.json

      - name: Validate JSON
        run: jq empty medya/images.json || (echo "Invalid JSON"; exit 1)

      - name: Commit & Push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add medya/images.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Otomatik: images.json güncellendi"
          git pull --rebase origin main
          git push origin HEAD:main
