name: Sesler Json Guncelle

on:
  schedule:
    - cron: "0 */4 * * *" # Her 4 saatte bir
  workflow_dispatch: # Manuel tetikleme için

jobs:
  sparse-checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Set up sparse-checkout for "kaynak" directory
      run: |
        git init
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/benolanben/atesiask.git
        git config core.sparseCheckout true
        echo "kaynak" >> .git/info/sparse-checkout
        git pull origin main

    - name: Define JSON File List
      id: define_list
      run: |
        # JSON dosya listesini tanımla
        FILES=("yunus.json" "aheng.json" "cocuk.json" "cuma.json" "hakikat.json" "hu_diyelim.json" 
               "mevlana.json" "muharrem.json" "nezih.json" "niyazi.json" "nutkuserif.json" 
               "ramazan.json" "saz.json" "tsm.json" "yeni_mestmp3.json")
        echo "files=${FILES[*]}" >> $GITHUB_ENV

    - name: Check and Update JSON Files
      run: |
        # Uzak dizindeki URL
        BASE_URL="https://kardelendergisi.com/atesiask/kaynak/"

        # JSON dosyalarını sırayla kontrol et
        for file in ${{ env.files }}; do
          echo "Checking $file"

          # Uzak dosyayı indir
          curl -s "${BASE_URL}${file}" -o "remote.json"

          # Yerel dosya yoksa boş bir JSON oluştur
          if [ ! -f "kaynak/${file}" ]; then
            echo '{"sesler": []}' > "kaynak/${file}"
          fi

          # Uzak dosyadaki sesler listesini ters çevir
          jq '.sesler |= reverse' remote.json > "remote_reversed.json"

          # Uzak ve yerel JSON uzunluklarını hesapla
          remote_length=$(jq '.sesler | length' remote_reversed.json)
          local_length=$(jq '.sesler | length' "kaynak/${file}")

          echo "Remote Length: $remote_length"
          echo "Local Length: $local_length"

          # Uzunlukları karşılaştır
          if [ "$remote_length" -ne "$local_length" ]; then
            echo "Differences found in $file. Updating local file."
            cat remote_reversed.json > "kaynak/${file}"

            # Değişiklikleri commit et
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add "kaynak/${file}"
            git commit -m "Update ${file} from remote with reversed 'sesler' list"
          else
            echo "No differences found in $file."
          fi
        done

        # Değişiklikleri push et
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/benolanben/atesiask.git HEAD:main
