name: Sozler Json Guncelle

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün saat 00:00'da
  workflow_dispatch: # Manuel tetikleme için

jobs:
  sparse-checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Set up sparse-checkout for "kaynak" directory
      run: |
        git init
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/benolanben/atesiask.git
        git config core.sparseCheckout true
        echo "kaynak" >> .git/info/sparse-checkout
        git pull origin main

    - name: Fetch Remote JSON
      run: |
        curl -s https://kardelendergisi.com/atesiask/kaynak/sozler.json -o remote.json

    - name: Compare and Update JSON
      run: |
        if [ ! -f kaynak/sozler.json ]; then
          echo '{"sozler": []}' > kaynak/sozler.json
        fi

        remote_length=$(jq '.sozler | length' remote.json)
        local_length=$(jq '.sozler | length' kaynak/sozler.json)

        echo "Remote List Length: $remote_length"
        echo "Local List Length: $local_length"

        if [ "$remote_length" -ne "$local_length" ]; then
          echo "Lists are different. Updating local JSON."
          cat remote.json > kaynak/sozler.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add kaynak/sozler.json
          git commit -m "Update kaynak/sozler.json from remote"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/benolanben/atesiask.git HEAD:main
        else
          echo "Lists are the same. No update needed."
        fi
